### ISSUE TITLE
Assemble Basic Robot Kit

### ISSUE THREAD

**Issue by silverlightning926** [Stealth-Robotics/FTC#2]
Current List For Basic Robot Kit:

- Rev Robotics Kit
- Control Hub
- Other Rev Hub
- Power Switch
- FTC Battery
- FTC Battery Charger
- GoBilda Mechanum Wheels
- Driver Phone
- GamePad
- PixyCam
- Hack Saw

**Comment by silverlightning926** [comment]
@kevinwross would you happen to have another camera like the one in the picture you could send over to?![20200922_213518.jpg](https://user-images.githubusercontent.com/38925407/93967247-a60c7500-fd1b-11ea-887b-a7b0751dde8d.jpg)

**Comment by kevinwross** [comment]
Sid, I do not have such a camera. I wonder if Jim might?
